# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Version of trunk to use
        description: 'Trunk Version'
        # Default value if no value is explicitly provided
        default: '0.16.0'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Using version ${{ github.event.inputs.version }} of trunk",
        wget -qO- https://github.com/thedodd/trunk/releases/download/${{ github.event.inputs.version }}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-,
        trunk build --release
        
